version: '3.8'

services:
  taxreturnapi:
    build:
      context: .
      dockerfile: WebApi/TaxReturnAPI/Dockerfile
    ports:
      - "5000:5000"
      - "5001:5001"
    environment:
      - ASPNETCORE_URLS=http://+:5000
      - DOTNET_RUNNING_IN_CONTAINER=true